# Generated by Django 3.1 on 2020-10-12 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroom_img', models.ImageField(blank='True', max_length=255, null='True', upload_to='')),
                ('kitchen_img', models.ImageField(blank='True', max_length=255, null='True', upload_to='')),
                ('bathroom_img', models.ImageField(blank='True', max_length=255, null='True', upload_to='')),
                ('livingroom_img', models.ImageField(blank='True', max_length=255, null='True', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_img', models.ImageField(blank='True', max_length=255, null='True', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water_facility', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('Parking_facility', models.BooleanField(default=False)),
                ('short_description', models.TextField(max_length=500)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_property.location')),
                ('room_images', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='add_property.roomimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('bedroom_no', models.IntegerField()),
                ('kitchen_no', models.IntegerField()),
                ('bathroom_no', models.IntegerField()),
                ('livingroom_no', models.IntegerField()),
                ('water_facility', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('Parking_facility', models.BooleanField(default=False)),
                ('short_description', models.TextField(max_length=500)),
                ('flat_images', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='add_property.flatimage')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_property.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
